version: "2"

linters:
  enable:
    - errcheck        # Check for unchecked errors
    - gocritic        # Extensive code quality checks
    - gosec           # Security-focused static analysis
    - prealloc        # Suggest preallocating slices
    - unconvert       # Detect unnecessary type conversions
    - unparam         # Find unused function parameters
    - goconst         # Find repeated strings that could be constants
    - misspell        # Find commonly misspelled words
    - nolintlint      # Ensure nolint directives are properly formatted
    - errorlint       # Find issues with error wrapping
    - exhaustive      # Check exhaustiveness of enum switch statements
    - nilerr          # Find code that returns nil instead of error
    - whitespace      # Detect leading/trailing whitespace issues

output:
  formats:
    text:
      print-linter-name: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
