# https://taskfile.dev

version: '3'

vars:
  CURRENT_DIR:
    sh: pwd

tasks:
  default:
    cmds:
      - task --list-all

  lint:
    cmds:
      - docker run --rm -v {{toSlash .CURRENT_DIR}}:/app -w /app golangci/golangci-lint:v1.50.1 golangci-lint run -v --timeout 5m

  upgrade-libraries:
    cmds:
      - go get -u ./...
      - go fmt ./...
      - go mod tidy
      - go mod verify

  tidy:
    cmds:
      - go fmt ./...
      - go mod tidy -v

  audit:
    cmds:
      - go vet ./...
      - go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-U1000 ./...
      - go mod verify

  build-runner:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -ldflags='-s' -o=./bin/linux_amd64/web ./cmd/web

  run:
    cmds:
      - ./bin/web

  build-goose:
    cmds:
      - CGO_ENABLED=1 go build -o ./migrate realworldgo.rasc.ch/cmd/migrate
    sources:
      - ./cmd/migrate/*.go
    generates:
      - ./migrate

  db-migration-new-newl:
    deps: [build-goose]
    cmds:
      - ./migrate create {{.CLI_ARGS}} sql

  db-migration-new-go:
    deps: [build-goose]
    cmds:
      - ./migrate create {{.CLI_ARGS}} go

  db-migration-up:
    deps: [build-goose]
    cmds:
      - ./migrate up

  db-migration-reset:
    deps: [build-goose]
    cmds:
      - ./migrate reset

  db-migration-status:
    deps: [build-goose]
    cmds:
      - ./migrate status

  db-codegen:
    cmds:
      - docker build -t sqlboilercodegen -f sqlboiler/Dockerfile .
      - docker run -v {{toSlash .CURRENT_DIR}}:/src sqlboilercodegen



