output = "../internal/models"
wipe = "true"
no-hooks = "true"
no-auto-timestamps = "true"
no-rows-affected = "true"
no-tests = "true"
add-enum-types = true

[sqlite3]
dbname = "/src/db.sqlite"
blacklist = ["goose_db_version"]
