// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Article         string
	ArticleFavorite string
	ArticleTag      string
	Comment         string
	Follow          string
	Sessions        string
	Tag             string
	User            string
}{
	Article:         "article",
	ArticleFavorite: "article_favorite",
	ArticleTag:      "article_tag",
	Comment:         "comment",
	Follow:          "follow",
	Sessions:        "sessions",
	Tag:             "tag",
	User:            "user",
}
